// Sample data for TechStream - Placeholder data to be replaced with real API data

export const heroSlides = [
  {
    id: '1',
    type: 'movie' as const,
    title: 'Avatar: The Way of Water',
    backdrop: '/hero-bg.png',
    year: 2022,
    rating: 8.0,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
    duration: 192,
    description: 'Jake Sully lives with his newfound family formed on the extrasolar moon Pandora. Once a familiar threat returns to finish what was previously started, Jake must work with Neytiri and the army of the Na\'vi race to protect their home.',
    isTrending: true,
  },
  {
    id: '2',
    type: 'series' as const,
    title: 'The Last of Us',
    backdrop: '/hero-bg.png',
    year: 2023,
    rating: 8.8,
    genre: ['Drama', 'Action', 'Adventure'],
    seasons: 1,
    description: 'After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity\'s last hope.',
    isTrending: true,
  },
  {
    id: '3',
    type: 'movie' as const,
    title: 'Oppenheimer',
    backdrop: '/hero-bg.png',
    year: 2023,
    rating: 8.6,
    genre: ['Drama', 'History'],
    duration: 180,
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    isTrending: true,
  },
]

export const movies = [
  {
    id: 'm1',
    title: 'Dune: Part Two',
    poster: '/movie-placeholder.jpg',
    year: 2024,
    rating: 8.7,
    duration: 166,
    genre: ['Sci-Fi', 'Action', 'Drama'],
    isNew: true,
    isTrending: true,
    isPremium: true,
  },
  {
    id: 'm2',
    title: 'Spider-Man: Across the Spider-Verse',
    poster: '/movie-placeholder.jpg',
    year: 2023,
    rating: 8.8,
    duration: 140,
    genre: ['Animation', 'Action', 'Adventure'],
    isTrending: true,
  },
  {
    id: 'm3',
    title: 'The Batman',
    poster: '/movie-placeholder.jpg',
    year: 2022,
    rating: 8.1,
    duration: 176,
    genre: ['Action', 'Crime', 'Drama'],
  },
  {
    id: 'm4',
    title: 'Top Gun: Maverick',
    poster: '/movie-placeholder.jpg',
    year: 2022,
    rating: 8.3,
    duration: 131,
    genre: ['Action', 'Drama'],
  },
  {
    id: 'm5',
    title: 'Black Panther: Wakanda Forever',
    poster: '/movie-placeholder.jpg',
    year: 2022,
    rating: 7.1,
    duration: 161,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
  },
  {
    id: 'm6',
    title: 'Everything Everywhere All at Once',
    poster: '/movie-placeholder.jpg',
    year: 2022,
    rating: 7.9,
    duration: 139,
    genre: ['Action', 'Adventure', 'Comedy'],
  },
]

export const series = [
  {
    id: 's1',
    title: 'Wednesday',
    poster: '/series-placeholder.jpg',
    year: 2022,
    rating: 8.2,
    seasons: 1,
    genre: ['Comedy', 'Crime', 'Fantasy'],
    isTrending: true,
    isOriginal: true,
  },
  {
    id: 's2',
    title: 'House of the Dragon',
    poster: '/series-placeholder.jpg',
    year: 2022,
    rating: 8.5,
    seasons: 1,
    genre: ['Action', 'Adventure', 'Drama'],
    isOriginal: true,
  },
  {
    id: 's3',
    title: 'Stranger Things',
    poster: '/series-placeholder.jpg',
    year: 2022,
    rating: 8.7,
    seasons: 4,
    genre: ['Drama', 'Fantasy', 'Horror'],
    isTrending: true,
    isOriginal: true,
  },
  {
    id: 's4',
    title: 'The Crown',
    poster: '/series-placeholder.jpg',
    year: 2020,
    rating: 8.6,
    seasons: 5,
    genre: ['Biography', 'Drama', 'History'],
    isOriginal: true,
  },
  {
    id: 's5',
    title: 'Squid Game',
    poster: '/series-placeholder.jpg',
    year: 2021,
    rating: 8.0,
    seasons: 1,
    genre: ['Action', 'Drama', 'Mystery'],
    isTrending: true,
    isOriginal: true,
  },
  {
    id: 's6',
    title: 'Breaking Bad',
    poster: '/series-placeholder.jpg',
    year: 2008,
    rating: 9.5,
    seasons: 5,
    genre: ['Crime', 'Drama', 'Thriller'],
  },
]

export const continueWatching = [
  {
    id: 'cw1',
    title: 'The Last of Us',
    poster: '/series-placeholder.jpg',
    year: 2023,
    rating: 8.8,
    seasons: 1,
    genre: ['Drama', 'Action'],
    progress: 65,
    type: 'series' as const,
  },
  {
    id: 'cw2',
    title: 'Dune: Part Two',
    poster: '/movie-placeholder.jpg',
    year: 2024,
    rating: 8.7,
    duration: 166,
    genre: ['Sci-Fi', 'Action'],
    progress: 30,
    type: 'movie' as const,
  },
]

export const africanMovies = [
  {
    id: 'af1',
    title: 'Black Panther',
    poster: '/movie-placeholder.jpg',
    year: 2018,
    rating: 7.3,
    duration: 134,
    genre: ['Action', 'Adventure', 'Sci-Fi'],
  },
  {
    id: 'af2',
    title: 'Queen of Katwe',
    poster: '/movie-placeholder.jpg',
    year: 2016,
    rating: 7.4,
    duration: 124,
    genre: ['Biography', 'Drama', 'Sport'],
  },
  {
    id: 'af3',
    title: 'The Boy Who Harnessed the Wind',
    poster: '/movie-placeholder.jpg',
    year: 2019,
    rating: 7.6,
    duration: 113,
    genre: ['Biography', 'Drama'],
    isOriginal: true,
  },
]
